export type ArchivedFicheExportData = {
  school_name: string;
  exam_session: string;
  candidate_full_name: string;
  candidate_number: string;
  class_name: string;
  epreuve: string;
  mcv_option: string;
  fiche_number: string;
  fiche_title: string;
  company_name: string;
  pfmp_period: string;
  situation_date: string;
  student_role: string;
  realization_conditions: string;
  context: string;
  customer_need: string;
  proposed_offer: string;
  argumentation: string;
  professional_communication: string;
  conclusion: string;
  updated_at: string;
  archived_at: string;
};
